name: PR Merge Validation

on:
  pull_request:
    branches:
      - main  # Target branch for PR (can be 'master' or any other branch)

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java (JDK 11) with Zulu JDK distribution
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'   # Using Zulu JDK (Azul OpenJDK)

      # Compile the Java program (if needed)
      - name: Compile Java Program
        run: javac src/main/java/RandomPRCheck.java

      # Run the Java program to determine if PR can be merged
      - name: Run Random Merge Check
        run: |
          java RandomPRCheck
          
      # The exit code of the Java program determines the PR outcome
      - name: Handle PR Outcome
        if: ${{ failure() }}
        run: |
          echo "PR cannot be merged!"
        continue-on-error: true
