name: PR Validation

on:
  pull_request:
    branches:
      - master  # Make sure it's targeting the correct branch, in your case `main`

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu image

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Step 3: Compile and run the test
      - name: Compile and run the test
        run: |
          javac RandomTest.java
          java RandomTest
